#!/bin/sh

cd /var/www
#ln -s /data/uploads storage/app/public
#ln -s /data/secured storage/secured
chmod 777 -R storage bootstrap/cache

cp .env.prod .env
./artisan config:cache
./artisan route:cache
./artisan optimize

touch /root/.app_laravel_inited

